# Generated by Django 4.1 on 2022-08-21 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('editada', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=400, verbose_name='Subtítulo')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('imagen', models.ImageField(upload_to='noticias', verbose_name='Imagen')),
                ('publicada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('editada', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categorias', models.ManyToManyField(to='noticias.categoria', verbose_name='Categorías')),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
                'ordering': ['-creada'],
            },
        ),
    ]
