# Generated by Django 4.1 on 2022-08-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-publicada'], 'verbose_name': 'noticia', 'verbose_name_plural': 'noticias'},
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='creada',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='editada',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
