# Generated by Django 4.1 on 2022-08-24 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_noticia_options_remove_noticia_categorias_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha'], 'verbose_name': 'noticia', 'verbose_name_plural': 'noticias'},
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='publicada',
        ),
        migrations.AddField(
            model_name='noticia',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
